server:
  port: 7020
spring:
  application:
    name: sgai-bems-baotou
  config:
    import:
      - optional:nacos:jeecg.yaml
      - optional:nacos:bems-baotou-dev.yaml
  cloud:
    nacos:
      config:
        server-addr: 192.168.204.51:8848
        group: DEFAULT_GROUP
        namespace: public
        username:
        password:
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
        namespace: public
        username:
        password:
        group: DEFAULT_GROUP
bems:
  integration:
    enabled: true
    token:
      meter: bems_energy
      equipment: bems_building
    source: sgai-bems
    master:
      base-url: http://10.77.16.5/jeecgboot
      receive-path: /master/integration/receive
    push:
      timeout-seconds: 5
    gas:
      url: http://192.168.3.63:8080/RealData
      tagids:
    hydrogen:
      url: http://192.168.3.63:8080/RealData
      tagids:
    point:
      url: http://192.168.3.63:8080/Point